# =========================
# Configuracion de Spring
# =========================
spring:
  application:
    name: ms-cajaahorro-user

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://turntable.proxy.rlwy.net:17419/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:gCiXwshILdjFsegheCyvAdUYdjTHMfmx}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update    # o validate, none, según tu necesidad
    defer-datasource-initialization: true

# =========================
# Configuracion del servidor
# =========================
server:
  port: ${PORT:8088}   # Railway asigna el puerto dinámicamente

# =========================
# Configuracion del cliente de Eureka
# =========================
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOST:ms-cajaahorro-user}

# =========================
# Logging opcional
# =========================
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix.discovery: DEBUG
