

spring:
  application:
    name: ms-cajaahorro-user

    server:
      port: ${PORT:0}    # 0 permite que Railway asigne un puerto automáticamente

  datasource:
    url: jdbc:postgresql://${DB_HOST:turntable.proxy.rlwy.net}:${DB_PORT:17419}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:gCiXwshILdjFsegheCyvAdUYdjTHMfmx}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ⚠️ cámbialo según tu necesidad: validate / none / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: https://${RAILWAY_PUBLIC_DOMAIN:ms-eureka.up.railway.app}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: false
