server:
  port: ${PORT}   # Railway inyecta automáticamente PORT, por defecto 8080

spring:
  application:
    name: ms-cajaahorro-user

  datasource:
    url: jdbc:postgresql://${DB_HOST:turntable.proxy.rlwy.net}:${DB_PORT:17419}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:gCiXwshILdjFsegheCyvAdUYdjTHMfmx}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ⚠️ cámbialo según tu necesidad: validate / none / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka.up.railway.app/eureka}
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: false
    hostname: ${RAILWAY_PUBLIC_DOMAIN:ms-cajaahorro-user.up.railway.app}  # dominio público Railway
    non-secure-port: ${PORT:8080}
    instance-id: ${spring.application.name}:${random.value}
