## Configuracion de Spring
spring:
  application:
    name: ms-cajaahorro-user
  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:17419/postgres
    username: postgres
    password: gCiXwshILdjFsegheCyvAdUYdjTHMfmx
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
    ##  ddl-auto: create-drop
    defer-datasource-initialization: true
## Configuracion de Instancia
server:
  port: 8088
## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-cajaahorro-user


