## Configuración de Spring
spring:
  application:
    name: ms-cajaahorro-user
  datasource:
    url: jdbc:postgresql://${DB_HOST:turntable.proxy.rlwy.net}:${DB_PORT:17419}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:gCiXwshILdjFsegheCyvAdUYdjTHMfmx}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update  # Cambiar según necesidad: none, validate, update, create, create-drop
    defer-datasource-initialization: true

server:
  port: ${PORT:0}  # Railway asigna un puerto automáticamente

## Configuración de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-production-6f23.up.railway.app/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${RAILWAY_PUBLIC_DOMAIN:ms-cajaahorro-user.up.railway.app}
    instance-id: ${spring.application.name}:${random.value}
